### ISSUE TITLE
Dataset availability?

### ISSUE THREAD

**Issue by jerofad** [antho-data/Retinal_Disease_Classification#1]
Hey I was was wondering if you can point me to the datasets repository you used for this with the 46 classes 

Or is it a private data that cannot be shared?

TIA

**Comment by antho-data** [comment]
Hello Jerofad,

You will find the dataset on kaggle :

https://www.kaggle.com/andrewmvd/retinal-disease-classification/code

Hope this help !

**Comment by jerofad** [comment]
Oh it does. Thanks
